### PR TITLE
Shared extension

### PR DESCRIPTION
**Pull request by marko-bekhta**

### CODE REVIEW

**Comment by marko-bekhta** [comment]
If we merge this... we'd need to:

- update the CI job name
- rename the repository
- do a 3.0.0 release. Or should we start with the 1.0.0 as the group/artifact changed?
- update Search/Validator to use the new extension version

**Review by yrodiere — APPROVED** [review]

**Comment by yrodiere** [comment]
> If we merge this

Done

> ... we'd need to:
> 
>     * update the CI job name

Done

>     * rename the repository

Done

>     * do a 3.0.0 release. Or should we start with the 1.0.0 as the group/artifact changed?
> 
>     * update Search/Validator to use the new extension version

Please do? :)

**Comment by yrodiere** [comment]
3.0.0 seems fine BTW

**Comment by yrodiere** [comment]
And thank you! :)

**Pull request merged**
